AWSTemplateFormatVersion: '2010-09-09'
Description: "flows clevver"
Resources:
  newinvoiceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: newinvoice
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  newinvoiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${newinvoiceFunction}"
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - Fn::GetAtt: [ newinvoiceFunction , Arn ]
Outputs:
  newinvoiceFunction:
    Description: 'newinvoice'
    Value:
      Fn::GetAtt: [ newinvoiceFunction , Arn ]
  newinvoiceRole:
    Description: 'newinvoice'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
